### ISSUE TITLE
Display success or failure on Login

### ISSUE THREAD

**Issue by knhumbarger** [ZergRushJoe/databaseExp#17]
Currently prints to console whether or not log was successful, would be better if it displayed the success or failure status on the page.

**Comment by ZergRushJoe** [comment]
Can you give me some more information like a code snip of  the api doing the login.

**Comment by ZergRushJoe** [comment]
ok so what you need to do in place of the console.log in login.js
`document.getElementById('display').innerhtml = \\what ever the res was from the server`
then add an h2 tag to the pug view with the id of display
